### PR TITLE
Documentation

### LINKED ISSUE #34: forgot password is sending wrong token
think you have some async issue going on... the reset password is not emailing the newly created token, it's sending the previously stored one or null

### LINKED ISSUE #35: email confirmation tokens are too long
shrink them to 8 characters

### LINKED ISSUE #36: use Errror object for throw and promise rejections instead of string literals
Try resolving those promise rejections and throws in  [here](https://github.com/UPE-FIU/Turtle/blob/master/src/services/application.js) using the [Error Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Used_as_a_function) instead 

you can read the docs here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#Description

### PR DESCRIPTION
**Pull request by Barnes2197**
Fixed #34 
Fixed #36 
Closed #35

### CODE REVIEW

File: src/models/applicant.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ const applicantSchema = new mongoose.Schema({
   resetPasswordToken: { type: String },
   resetPasswordExpiration: { type: Date },
   schoolName: { type: String },
+  avatarID: {type: String},
```
Comment (Tommy2016x) [inline src/models/applicant.js]: keep the spacing consistent with the rest
